---

name: Remove Labels
on:
  issue_comment:
    types: [created, edited]
jobs:
  remove-labels:
    if: ${{ github.actor != 'Tom Selander' &&  github.actor != 'patrickfreed'
        && github.actor != 'abr-egn' && github.actor != 'isabelatkinson'}}
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          remove-labels: "waiting-for-reporter, Stale"
